//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TZLockerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Locker
    {
        public int Locker_id { get; set; }
        public Nullable<int> LockerBank_id { get; set; }
        public string LockerName { get; set; }
    }
}
